ALTER TABLE movies ADD COLUMN IF NOT EXISTS genre_ids INTEGER[] NOT NULL DEFAULT '{}';
ALTER TABLE movies ADD COLUMN IF NOT EXISTS collection_id INTEGER;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS collection_name TEXT;
